server:
  port: 8080

tsf:
  swagger:
    enabled: true

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  auto-runtime-dialect: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000